tets

diff --git a/instance-applications/115-ibm-aibroker-tenant/templates/08-aibroker-postsyncjob copy.yaml b/instance-applications/115-ibm-aibroker-tenant/templates/08-aibroker-postsyncjob copy.yaml
--- a/instance-applications/115-ibm-aibroker-tenant/templates/08-aibroker-postsyncjob copy.yaml
+++ b/instance-applications/115-ibm-aibroker-tenant/templates/08-aibroker-postsyncjob copy.yaml
@@ -1,7 +1,8 @@
 {{- /*
 Meaningful prefix for the job resource name. Must be under 52 chars in length to leave room for the 11 chars reserved for '-' and $_job_hash.
 */}}
-{{- $_job_name_prefix := "mas-manage-ai-tenant" }}{{- /*
+{{- $_job_name_prefix := "mas-manage-ai-tenant" }}
+{{- /*
 Use the build/bin/set-cli-image-digest.sh script to update this value across all charts.
 Included in $_job_hash (see below).
 */}}
@@ -23,7 +24,9 @@ Included in $_job_hash (see below).
 This is to ensure ArgoCD will create a new job resource intead of attempting (and failing) to update an
 immutable field of any existing Job resource.
 */}}
-{{- $_job_hash := print ($_job_config_values | toYaml) $_cli_image_digest $_job_version | adler32sum }}{{- $_job_name := join "-" (list $_job_name_prefix $_job_hash )}}{{- /*
+{{- $_job_hash := print ($_job_config_values | toYaml) $_cli_image_digest $_job_version | adler32sum }}
+{{- $_job_name := join "-" (list $_job_name_prefix $_job_hash )}}
+{{- /*
 Set as the value for the mas.ibm.com/job-cleanup-group label on the Job resource.When the auto_delete flag is not set on the root application, a CronJob in the cluster uses this label 
 to identify old Job resources that should be pruned on behalf of ArgoCD.Any Job resources in the same namespace that have the mas.ibm.com/job-cleanup-group with this value
 will be considered to belong to the same cleanup group. All but the most recent (i.e. with the latest "creation_timestamp")
@@ -50,10 +53,13 @@ metadata:
   annotations:
     argocd.argoproj.io/sync-wave: "310"
 rules:
-  - apiGroups: [""]
-    resources: ["secrets"]
-    verbs: ["get", "list", "watch"]
-
+- apiGroups:
+    - ""
+  resources:
+    - pods
+  verbs:
+    - list
+    - get
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
@@ -71,13 +77,30 @@ roleRef:
   name: mas-manage-aiservice-job-role
   apiGroup: rbac.authorization.k8s.io
 ---
+apiVersion: networking.k8s.io/v1
+kind: NetworkPolicy
+metadata:
+  name: allow-mas-manage-ai-tenant-job
+  namespace: "{{ .Values.aibroker_namespace }}"
+  annotations:
+    argocd.argoproj.io/sync-wave: "312"
+spec:
+  podSelector:
+    matchLabels:
+      app: {{ $job_name }}
+  egress:
+    - {}
+  policyTypes:
+    - Egress
+
+---
 apiVersion: batch/v1
 kind: Job
 metadata:
   name: {{ $_job_name }}
   namespace: "{{ .Values.aibroker_namespace }}"
   annotations:
-    argocd.argoproj.io/sync-wave: "312"
+    argocd.argoproj.io/sync-wave: "313"
   labels:
     mas.ibm.com/job-cleanup-group: {{ $_job_cleanup_group }}
 {{- if .Values.custom_labels }}
@@ -87,7 +110,7 @@ spec:
   template:
     metadata:
       labels:
-        app: sync-job
+        app: {{ $job_name }}
 {{- if .Values.custom_labels }}
 {{ .Values.custom_labels | toYaml | indent 8 }}
 {{- end }}
@@ -98,6 +121,13 @@ spec:
         - name: mas-manage-aiservice-run
           image: quay.io/ibmmas/cli@{{ $_cli_image_digest }}
           imagePullPolicy: IfNotPresent
+          resources:
+            limits:
+              cpu: 200m
+              memory: 512Mi
+            requests:
+              cpu: 10m
+              memory: 64Mi
           env:
             - name: ACCOUNT_ID
               value: "{{ .Values.account_id }}"
@@ -105,8 +135,6 @@ spec:
               value: "{{ .Values.cluster_id }}"
             - name: AIBROKER_INSTANCE_ID
               value: "{{ .Values.aibroker_instance_id }}"
-            - name: AIBROKER_NAMESPACE
-              value: "{{ .Values.aibroker_namespace }}"
             - name: SECRETS_KEY_SEPERATOR
               value: "/"
             - name: AIBROKER_TENANT
@@ -128,47 +156,46 @@ spec:
               SECRET_NAME_AISERVICE=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${AIBROKER_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}aiservice
 
               echo "================================================================================"
-              echo "Settings"
-              echo "================================================================================"
-              echo "Account Id ....................... ${ACCOUNT_ID}"
-              echo "Cluster Id ....................... ${CLUSTER_ID}"
-              echo "AIBROKER Instance Id ............. ${AIBROKER_INSTANCE_ID}"
-              echo "AIBROKER NAMESPACE ................. ${AIBROKER_NAMESPACE}"
-              echo "SM_AWS_REGION .................... ${SM_AWS_REGION}"
-              echo "SM_AWS_ACCESS_KEY_ID ............ ${SM_AWS_ACCESS_KEY_ID:0:4}<snip>"
-              echo "SM_AWS_SECRET_ACCESS_KEY ........ ${SM_AWS_SECRET_ACCESS_KEY:0:4}<snip>"
-              echo "SECRET_NAME_AISERVICE .................... ${SECRET_NAME_AISERVICE}"
+              #oc get pods -n mas-aibroker-inst-1-aibroker
+              # echo "Settings"
+              # echo "================================================================================"
+              # echo "Account Id ....................... ${ACCOUNT_ID}"
+              # echo "Cluster Id ....................... ${CLUSTER_ID}"
+              # echo "AIBROKER Instance Id ............. ${AIBROKER_INSTANCE_ID}"
+              # echo "SM_AWS_REGION .................... ${SM_AWS_REGION}"
+              # echo "SM_AWS_ACCESS_KEY_ID ............ ${SM_AWS_ACCESS_KEY_ID:0:4}<snip>"
+              # echo "SM_AWS_SECRET_ACCESS_KEY ........ ${SM_AWS_SECRET_ACCESS_KEY:0:4}<snip>"
+              # echo "SECRET_NAME_AISERVICE .................... ${SECRET_NAME_AISERVICE}"
 
-              echo "================================================================================"
-              echo "Retrieve AIBroker API Key for tenant: ${AIBROKER_TENANT}"
-              echo "================================================================================"
-              oc get secret provision-tenant----apikey-secret -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.AIBROKER_APIKEY}" | base64 --decode
-              export AIBROKER_APIKEY_SECRET=$(oc get secret ${AIBROKER_TENANT}----apikey-secret -n ${AIBROKER_NAMESPACE} -o jsonpath="{.data.AIBROKER_APIKEY}" | base64 --decode)
-              #oc get secret provision-tenant----apikey-secret -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.AIBROKER_APIKEY}" | base64 --decode
-              export AIBROKER_APIKEY_SECRET=$(oc get secret ${AIBROKER_TENANT}----apikey-secret -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.AIBROKER_APIKEY}" | base64 --decode)
-              echo "AIBROKER_APIKEY_SECRET .................... ${AIBROKER_APIKEY_SECRET}"
-              if [ -z "$AIBROKER_APIKEY_SECRET" ]; then
-                echo "Failed to retrieve AIBroker API Key"
-              echo "AIBROKER_APIKEY_SECRET = ${AIBROKER_APIKEY_SECRET:0:4}<snip>"
+              # echo "================================================================================"
+              # echo "Retrieve AIBroker API Key for tenant: ${AIBROKER_TENANT}"
+              # echo "================================================================================"
+              
+              # #oc get secret provision-tenant----apikey-secret -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.AIBROKER_APIKEY}" | base64 --decode
+              # export AIBROKER_APIKEY_SECRET=$(oc get secret ${AIBROKER_TENANT}----apikey-secret -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.AIBROKER_APIKEY}" | base64 --decode)
+              # echo "AIBROKER_APIKEY_SECRET .................... ${AIBROKER_APIKEY_SECRET}"
+              # if [ -z "$AIBROKER_APIKEY_SECRET" ]; then
+              #   echo "Failed to retrieve AIBroker API Key"
+              #   exit 1
+              # fi
 
-              echo "Retrieve TLS Secrets"
-              export CA_CERT=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n ${AIBROKER_NAMESPACE} -o jsonpath="{.data.ca\\.crt}" | base64 --decode)
-              export TLS_CERT=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n ${AIBROKER_NAMESPACE} -o jsonpath="{.data.tls\\.crt}" | base64 --decode)
-              export TLS_KEY=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n ${AIBROKER_NAMESPACE} -o jsonpath="{.data.tls\\.key}" | base64 --decode)
-              export CA_CERT=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.ca\\.crt}" | base64 --decode)
-              export TLS_CERT=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.tls\\.crt}" | base64 --decode)
-              export TLS_KEY=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.tls\\.key}" | base64 --decode)
+              # echo "AIBROKER_APIKEY_SECRET = ${AIBROKER_APIKEY_SECRET:0:4}<snip>"
 
-              echo "CA_CERT = ${CA_CERT:0:20}<snip>"
-              echo "TLS_CERT = ${TLS_CERT:0:20}<snip>"
-              echo "TLS_KEY = ${TLS_KEY:0:20}<snip>"
+              # echo "Retrieve TLS Secrets"
+              # export CA_CERT=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.ca\\.crt}" | base64 --decode)
+              # export TLS_CERT=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.tls\\.crt}" | base64 --decode)
+              # export TLS_KEY=$(oc get secret ${AIBROKER_INSTANCE_ID}-public-aibroker-tls -n mas-aibroker-inst-1-aibroker -o jsonpath="{.data.tls\\.key}" | base64 --decode)
 
-              source /mascli/functions/gitops_utils
-              sm_login
+              # echo "CA_CERT = ${CA_CERT:0:20}<snip>"
+              # echo "TLS_CERT = ${TLS_CERT:0:20}<snip>"
+              # echo "TLS_KEY = ${TLS_KEY:0:20}<snip>"
 
-              TAGS='[{\"Key\": \"source\", \"Value\": \"mas-ai-service\"}, {\"Key\": \"account\", \"Value\": \"${ACCOUNT_ID}\"}, {\"Key\": \"cluster\", \"Value\": \"${CLUSTER_ID}\"}]'
+              # source /mascli/functions/gitops_utils
+              # sm_login
 
-              sm_update_secret $SECRET_NAME_AISERVICE "{\"aibroker_tenant\":\"$AIBROKER_TENANT\", \"aibroker_apikey\":\"$AIBROKER_APIKEY_SECRET\", \"cas_cert\":\"$CA_CERT\", \"tls_cert\":\"$TLS_CERT\", \"tls_key\":\"$TLS_KEY\"}" "$TAGS" || exit $?
+              # TAGS='[{\"Key\": \"source\", \"Value\": \"mas-ai-service\"}, {\"Key\": \"account\", \"Value\": \"${ACCOUNT_ID}\"}, {\"Key\": \"cluster\", \"Value\": \"${CLUSTER_ID}\"}]'
+
+              # sm_update_secret $SECRET_NAME_AISERVICE "{\"aibroker_tenant\":\"$AIBROKER_TENANT\", \"aibroker_apikey\":\"$AIBROKER_APIKEY_SECRET\", \"cas_cert\":\"$CA_CERT\", \"tls_cert\":\"$TLS_CERT\", \"tls_key\":\"$TLS_KEY\"}" "$TAGS" || exit $?
       volumes:
         - name: mas-manage-aiservice
           secret:
