correct

diff --git a/instance-applications/550-ibm-mas-addons-config/templates/06-nonshared-cluster-cr.yaml b/instance-applications/550-ibm-mas-addons-config/templates/06-nonshared-cluster-cr.yaml
--- a/instance-applications/550-ibm-mas-addons-config/templates/06-nonshared-cluster-cr.yaml
+++ b/instance-applications/550-ibm-mas-addons-config/templates/06-nonshared-cluster-cr.yaml
@@ -26,16 +26,16 @@ metadata:
   annotations:
     argocd.argoproj.io/sync-wave: "556"
     # Strong annotations to prevent ArgoCD from modifying the resource
-    argocd.argoproj.io/sync-options: Prune=false,Replace=false,ApplyOnly=true
+    argocd.argoproj.io/sync-options: Prune=false,Delete=false,Replace=false,ApplyOnly=true
     argocd.argoproj.io/compare-options: IgnoreExtraneous
   labels:
     mas.ibm.com/configScope: system
     mas.ibm.com/clusterResource: "true"
     # This label indicates this is a shared cluster resource
     mas.ibm.com/sharedResource: "true"
-{{- if .Values.custom_labels }}
-{{ .Values.custom_labels | toYaml | indent 4 }}
-{{- end }}
+  {{- if .Values.custom_labels }}
+  {{ .Values.custom_labels | toYaml | indent 4 }}
+  {{- end }}
 spec:
   displayName: "NonsharedCluster"
   addonType: nonsharedcluster
@@ -60,42 +60,42 @@ spec:
     spec:
       serviceAccountName: default
       containers:
-      - name: ensure
-        image: registry.redhat.io/openshift4/ose-cli:latest
-        command:
-        - /bin/bash
-        - -c
-        - |
-          echo "Starting ensure job for instance {{ .Values.instance_id }}"
-          
-          # Check if the GenericAddon exists
-          if ! oc get genericaddon cluster-addons-nonsharedcluster -n openshift-gitops &>/dev/null; then
-            echo "GenericAddon does not exist. Creating it..."
-            cat <<EOF | oc apply -f -
-          apiVersion: addons.mas.ibm.com/v1
-          kind: GenericAddon
-          metadata:
-            name: "cluster-addons-nonsharedcluster"
-            namespace: openshift-gitops
-            annotations:
-              argocd.argoproj.io/sync-options: Prune=false,Delete=false,Replace=false,ApplyOnly=true
-              argocd.argoproj.io/compare-options: IgnoreExtraneous
-            labels:
-              mas.ibm.com/configScope: system
-              mas.ibm.com/clusterResource: "true"
-              mas.ibm.com/sharedResource: "true"
-              app.kubernetes.io/managed-by: "mas-gitops"
-          spec:
-            displayName: "NonsharedCluster"
-            addonType: nonsharedcluster
-            config:
-              instances:
-                - name: "NonsharedCluster"
-          EOF
-            echo "GenericAddon created."
-          else
-            echo "GenericAddon already exists. No action needed."
-          fi
+        - name: ensure
+          image: registry.redhat.io/openshift4/ose-cli:latest
+          command:
+            - /bin/bash
+            - -c
+            - |
+              echo "Starting ensure job for instance {{ .Values.instance_id }}"
+              
+              # Check if the GenericAddon exists
+              if ! oc get genericaddon cluster-addons-nonsharedcluster -n openshift-gitops &>/dev/null; then
+                echo "GenericAddon does not exist. Creating it..."
+                cat <<EOF | oc apply -f -
+              apiVersion: addons.mas.ibm.com/v1
+              kind: GenericAddon
+              metadata:
+                name: "cluster-addons-nonsharedcluster"
+                namespace: openshift-gitops
+                annotations:
+                  argocd.argoproj.io/sync-options: Prune=false,Delete=false,Replace=false,ApplyOnly=true
+                  argocd.argoproj.io/compare-options: IgnoreExtraneous
+                labels:
+                  mas.ibm.com/configScope: system
+                  mas.ibm.com/clusterResource: "true"
+                  mas.ibm.com/sharedResource: "true"
+                  app.kubernetes.io/managed-by: "mas-gitops"
+              spec:
+                displayName: "NonsharedCluster"
+                addonType: nonsharedcluster
+                config:
+                  instances:
+                    - name: "NonsharedCluster"
+              EOF
+                echo "GenericAddon created."
+              else
+                echo "GenericAddon already exists. No action needed."
+              fi
       restartPolicy: Never
   backoffLimit: 3
 ---
@@ -116,24 +116,24 @@ spec:
     spec:
       serviceAccountName: default
       containers:
-      - name: cleanup-check
-        image: registry.redhat.io/openshift4/ose-cli:latest
-        command:
-        - /bin/bash
-        - -c
-        - |
-          echo "Starting cleanup check for instance {{ .Values.instance_id }}"
-          
-          # Check if there are any marker ConfigMaps other than this instance's
-          OTHER_MARKERS=$(oc get configmap -n openshift-gitops -l mas.ibm.com/nonsharedMarker=true --no-headers | grep -v nonshared-marker-{{ .Values.instance_id }} | wc -l)
-          
-          echo "Found $OTHER_MARKERS other instances using the GenericAddon"
-          
-          # No action needed - the GenericAddon will be managed by the ensure job
-          # and will be deleted by the disable-cleanup job when nonshared=false
+        - name: cleanup-check
+          image: registry.redhat.io/openshift4/ose-cli:latest
+          command:
+            - /bin/bash
+            - -c
+            - |
+              echo "Starting cleanup check for instance {{ .Values.instance_id }}"
+              
+              # Check if there are any marker ConfigMaps other than this instance's
+              OTHER_MARKERS=$(oc get configmap -n openshift-gitops -l mas.ibm.com/nonsharedMarker=true --no-headers | grep -v nonshared-marker-{{ .Values.instance_id }} | wc -l)
+              
+              echo "Found $OTHER_MARKERS other instances using the GenericAddon"
+              
+              # No action needed - the GenericAddon will be managed by the ensure job
+              # and will be deleted by the disable-cleanup job when nonshared=false
       restartPolicy: Never
   backoffLimit: 3
-{{- else }}
+  {{- else }}
 ---
 # Job to clean up resources when nonshared is set to false
 apiVersion: batch/v1
@@ -152,50 +152,29 @@ spec:
     spec:
       serviceAccountName: default
       containers:
-      - name: cleanup
-        image: registry.redhat.io/openshift4/ose-cli:latest
-        command:
-        - /bin/bash
-        - -c
-        - |
-          echo "Starting cleanup for nonshared=false"
-          
-          # Create a log file
-          LOG_FILE="/tmp/cleanup.log"
-          exec > >(tee -a "$LOG_FILE") 2>&1
-          
-          echo "$(date): Cleanup job running for instance {{ .Values.instance_id }}"
-          
-          # Delete the marker ConfigMap for this instance
-          echo "$(date): Deleting marker ConfigMap for this instance..."
-          oc delete configmap nonshared-marker-{{ .Values.instance_id }} -n openshift-gitops --ignore-not-found
-          
-          # Check if there are any other instances using this resource
-          echo "$(date): Checking for other marker ConfigMaps..."
-          MARKER_COUNT=$(oc get configmap -n openshift-gitops -l mas.ibm.com/nonsharedMarker=true --no-headers | wc -l)
-          echo "$(date): Found $MARKER_COUNT marker ConfigMaps"
-          
-          # Force delete the GenericAddon regardless of marker count when nonshared=false
-          echo "$(date): nonshared=false, deleting GenericAddon regardless of marker count..."
-          oc delete genericaddon cluster-addons-nonsharedcluster -n openshift-gitops --ignore-not-found
-          DELETE_RESULT=$?
-          echo "$(date): Delete command result: $DELETE_RESULT"
-          
-          if [ $DELETE_RESULT -eq 0 ]; then
-            echo "$(date): GenericAddon deleted successfully."
-          else
-            echo "$(date): Failed to delete GenericAddon. Trying with force..."
-            oc delete genericaddon cluster-addons-nonsharedcluster -n openshift-gitops --force --grace-period=0 --ignore-not-found
-          fi
-          
-          # Delete all marker ConfigMaps
-          echo "$(date): Deleting all marker ConfigMaps..."
-          oc delete configmap -n openshift-gitops -l mas.ibm.com/nonsharedMarker=true --ignore-not-found
-          
-          echo "$(date): Cleanup completed."
-          
-          # Save the log to a ConfigMap for debugging
-          echo "$(date): Creating log ConfigMap..."
-          oc create configmap nonshared-cleanup-log-{{ .Values.instance_id }} --from-file=cleanup.log="$LOG_FILE" -n openshift-gitops || true      restartPolicy: Never
+        - name: cleanup
+          image: registry.redhat.io/openshift4/ose-cli:latest
+          command:
+            - /bin/bash
+            - -c
+            - |
+              echo "Starting cleanup for nonshared=false"
+              
+              # Delete the marker ConfigMap for this instance
+              oc delete configmap nonshared-marker-{{ .Values.instance_id }} -n openshift-gitops --ignore-not-found
+              
+              # Check if there are any other instances using this resource
+              MARKER_COUNT=$(oc get configmap -n openshift-gitops -l mas.ibm.com/nonsharedMarker=true --no-headers | wc -l)
+              
+              if [ "$MARKER_COUNT" -eq "0" ]; then
+                echo "No other instances found using the nonshared cluster resource. Deleting the GenericAddon."
+                # Delete the GenericAddon
+                oc delete genericaddon cluster-addons-nonsharedcluster -n openshift-gitops --ignore-not-found
+              
+                echo "GenericAddon deleted."
+              else
+                echo "Found $MARKER_COUNT other instances still using the nonshared cluster resource. Keeping the GenericAddon."
+              fi
+      restartPolicy: Never
   backoffLimit: 3
-{{- end }}
+  {{- end }}
