cis-compliance post delete: delete both profilebundles. Add force logic.

diff --git a/applications/040-cis-compliance/templates/postdelete-delete-cr.yaml b/applications/040-cis-compliance/templates/postdelete-delete-cr.yaml
--- a/applications/040-cis-compliance/templates/postdelete-delete-cr.yaml
+++ b/applications/040-cis-compliance/templates/postdelete-delete-cr.yaml
@@ -1,14 +1,14 @@
 {{- if .Values.cis_compliance.use_postdelete_hooks }}
 
 # Generate a suffix for all the resources so there are no name clashes if >1 config is deleted at the same time
-{{ $cr_name := "ocp4" }}
+{{ $cr_names := "ocp4,rhcos4" }}
 {{ $cr_kind := "profilebundles" }}
 {{ $cr_api_version := "compliance.openshift.io" }}
-{{ $role_name := printf "postdelete-delete-cr-r-%s" $cr_name }}
-{{ $sa_name := printf "postdelete-delete-cr-sa-%s" $cr_name }}
-{{ $rb_name := printf "postdelete-delete-cr-rb-%s" $cr_name }}
-{{ $np_name := printf "postdelete-delete-cr-np-%s" $cr_name }}
-{{ $job_name := printf "postdelete-delete-cr-job-%s" $cr_name }}
+{{ $role_name := "postdelete-delete-profilebundles-r" }}
+{{ $sa_name := "postdelete-delete-profilebundles-sa" }}
+{{ $rb_name := "postdelete-delete-profilebundles-rb"}}
+{{ $np_name := "postdelete-delete-profilebundles-np" }}
+{{ $job_name := "postdelete-delete-profilebundles-job" }}
 {{ $ns := "openshift-compliance" }}
 {{ $hook_delete_policy := "HookSucceeded" }}
 
@@ -108,8 +108,8 @@ spec:
           env:
             - name: CR_NAMESPACE
               value: {{ $ns }}
-            - name: CR_NAME
-              value: {{ $cr_name }}
+            - name: CR_NAMES
+              value: {{ $cr_names }}
 
             - name: CR_API_VERSION
               value: {{ $cr_api_version }}
@@ -151,6 +151,14 @@ spec:
                 return_code=$?
                 set -e
 
+                if [ $return_code -ne 0 ]; then
+                  echo "oc delete timed out after 300s, forcing delete by removing finalizers"
+                  echo "oc patch $RESOURCE -n $NAMESPACE"
+
+                  # NOTE: set -e, so job will exit if this fails (which is what we want)
+                  oc patch $RESOURCE -n $NAMESPACE --type="json" -p '[{"op": "remove", "path":"/metadata/finalizers"}]' 2>/dev/null
+                fi
+
                 echo "Verify that resource $RESOURCE is now absent in namespace $NAMESPACE "
                 # don't want a non-zero rc from oc delete to cause the job to fail
                 # so, temporarily set +e
@@ -167,8 +175,10 @@ spec:
                 
               }
 
-              
-              delete_oc_resource "${CR_KIND}.${CR_API_VERSION}/${CR_NAME}" "${CR_NAMESPACE}"
+              for CR_NAME in ${CR_NAMES//,/ }; do
+                delete_oc_resource "${CR_KIND}.${CR_API_VERSION}/${CR_NAME}" "${CR_NAMESPACE}"
+              done
+
 
 
       restartPolicy: Never
