Add exit condition

diff --git a/instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml b/instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
--- a/instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
+++ b/instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
@@ -1031,6 +1031,11 @@ spec:
               oc set data cm $TEST_RECORD_CM test_passed=$TEST_PASSED
               oc set data cm $TEST_RECORD_CM --from-file=junitxml_test_output.xml
               oc set data cm $TEST_RECORD_CM --from-file=test_log.txt
+              
+              if [[ $TEST_PASSED == "false" ]]; then
+                echo "Test Result failed, exit 1"
+                exit 1
+              fi
 
       restartPolicy: Never
       serviceAccountName: {{ $sa_name }}
