remove oc project command

diff --git a/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml b/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
--- a/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
+++ b/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
@@ -1671,11 +1671,11 @@ spec:
               echo "oc whoami"
               oc whoami
               
-              CPD_NS_OUTPUT=$(oc project ${CPD_INSTANCE_NAMESPACE})
-              if [[ $CPD_NS_OUTPUT == *"not found"* ||  $CPD_NS_OUTPUT == *"Error"* ]]; then
-                echo "Failed to set context to the instance namespace"
-                exit 1
-              fi
+              # CPD_NS_OUTPUT=$(oc project ${CPD_INSTANCE_NAMESPACE})
+              # if [[ $CPD_NS_OUTPUT == *"not found"* ||  $CPD_NS_OUTPUT == *"Error"* ]]; then
+              #   echo "Failed to set context to the instance namespace"
+              #   exit 1
+              # fi
 
               while true; do
                 echo "first permission"
