split job into two

diff --git a/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml b/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
--- a/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
+++ b/instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
@@ -1626,8 +1626,8 @@ roleRef:
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: cpd-cmd-adm-policy-to-user-permissions
-  namespace: {{ .Values.cpd_instance_namespace }}
+  name: cpd-operators-user-permissions
+  namespace: {{ .Values.cpd_operators_namespace }}
   annotations:
     argocd.argoproj.io/sync-wave: "084"
 {{- if .Values.custom_labels }}
@@ -1659,8 +1659,6 @@ spec:
               value: {{ .Values.cpd_admin_login_sa }}
             - name: CPD_OPERATORS_NAMESPACE
               value: {{ .Values.cpd_operators_namespace }}
-            - name: CPD_INSTANCE_NAMESPACE
-              value: {{ .Values.cpd_instance_namespace }}
           command: 
             - /bin/sh
             - -c
@@ -1686,14 +1684,6 @@ spec:
               done
 
               while true; do
-                echo "second permission"
-                CPD_OPERANDS_NS_PERMISSION_OUTPUT=$(oc adm policy add-role-to-user admin --serviceaccount=${CPD_ADMIN_LOGIN_SA} --namespace=${CPD_INSTANCE_NAMESPACE} --rolebinding-name=cpd-instance-admin-rbac)
-                if [[ ${CPD_OPERANDS_NS_PERMISSION_OUTPUT} == *"clusterrole.rbac.authorization.k8s.io/admin added"* ]]; then
-                  break
-                fi
-              done
-
-              while true; do
                 echo "third permission"
                 CPD_APPLY_OLM_PERMISSION_OUTPUT=$(oc adm policy add-role-to-user cpd-instance-admin-apply-olm --serviceaccount=${CPD_ADMIN_LOGIN_SA} --namespace=${CPD_OPERATORS_NAMESPACE} --role-namespace=${CPD_OPERATORS_NAMESPACE} --rolebinding-name=cpd-instance-admin-apply-olm-rbac)
                 if [[ $CPD_APPLY_OLM_PERMISSION_OUTPUT == *"role.rbac.authorization.k8s.io/cpd-instance-admin-apply-olm added"*  ]]; then
@@ -1705,6 +1695,72 @@ spec:
                 echo "forth permission"
                 CPD_CATSRC_PERMISSION_OUTPUT=$(oc adm policy add-role-to-user cpd-instance-admin-read-catsrc --serviceaccount=${CPD_ADMIN_LOGIN_SA} --namespace=${CPD_OPERATORS_NAMESPACE} --role-namespace=${CPD_OPERATORS_NAMESPACE} --rolebinding-name=cpd-instance-admin-apply-olm-rbac)
                 if [[ ${CPD_CATSRC_PERMISSION_OUTPUT} == *"role.rbac.authorization.k8s.io/cpd-instance-admin-apply-olm added"* ]]; then
+                  break
+                fi
+              done
+
+      restartPolicy: Never
+      serviceAccountName: ibm-namespace-scope-operator
+  backoffLimit: 4
+
+
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: cpd-instance-user-permissions
+  namespace: {{ .Values.cpd_instance_namespace }}
+  annotations:
+    argocd.argoproj.io/sync-wave: "084"
+{{- if .Values.custom_labels }}
+  labels:
+{{ .Values.custom_labels | toYaml | indent 4 }}
+{{- end }}
+spec:
+  template:
+    {{- if .Values.custom_labels }}
+    metadata:
+      labels:
+    {{ .Values.custom_labels | toYaml | indent 8 }}
+    {{- end }}
+    spec:
+      containers:
+        - name: run
+          # Just using CLI because all the other jobs are using it too
+          image: quay.io/ibmmas/cli:9.0.0-pre.gitops
+          imagePullPolicy: IfNotPresent
+          resources:
+            limits:
+              cpu: 200m
+              memory: 512Mi
+            requests:
+              cpu: 10m
+              memory: 64Mi
+          env:
+            - name: CPD_ADMIN_LOGIN_SA
+              value: {{ .Values.cpd_admin_login_sa }}
+            - name: CPD_INSTANCE_NAMESPACE
+              value: {{ .Values.cpd_instance_namespace }}
+          command: 
+            - /bin/sh
+            - -c
+            - |
+
+              set -e
+
+              echo "oc whoami"
+              oc whoami
+              
+              # CPD_NS_OUTPUT=$(oc project ${CPD_INSTANCE_NAMESPACE})
+              # if [[ $CPD_NS_OUTPUT == *"not found"* ||  $CPD_NS_OUTPUT == *"Error"* ]]; then
+              #   echo "Failed to set context to the instance namespace"
+              #   exit 1
+              # fi
+
+              while true; do
+                echo "second permission"
+                CPD_OPERANDS_NS_PERMISSION_OUTPUT=$(oc adm policy add-role-to-user admin --serviceaccount=${CPD_ADMIN_LOGIN_SA} --namespace=${CPD_INSTANCE_NAMESPACE} --rolebinding-name=cpd-instance-admin-rbac)
+                if [[ ${CPD_OPERANDS_NS_PERMISSION_OUTPUT} == *"clusterrole.rbac.authorization.k8s.io/admin added"* ]]; then
                   break
                 fi
               done
