[patch] fix errors and more cpd updates

diff --git a/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml b/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml
--- a/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml
+++ b/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml
@@ -349,6 +349,14 @@ spec:
               fi
 
               echo
+              echo "Fetching Opencontent Opensearch Channel..."
+              export OPENSEARCH_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.opencontent_opensearch.sub_channel')
+              if [[ -z "${OPENSEARCH_CHANNEL}" ]]; then
+                echo "Failed to fetch opencontent opensearch channel"
+                exit 1
+              fi
+
+              echo
               echo "Fetching SPSS Version..."
               export SPSS_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.spss.cr_version')
               if [[ -z "${SPSS_VERSION}" ]]; then
@@ -395,6 +403,7 @@ spec:
               SECRET_NAME_DATAREFINERY_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/datarefinery_channel
               SECRET_NAME_RABBITMQ_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/opencontent_rabbitmq_channel
               SECRET_NAME_ELASTICSEARCH_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/opencontent_elasticsearch_channel
+              SECRET_NAME_OPENSEARCH_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/opencontent_opensearch_channel
               SECRET_NAME_SPSS_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spss_version
               SECRET_NAME_SPSS_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spss_channel
               SECRET_NAME_CANVASBASE_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/canvasbase_channel
@@ -429,6 +438,7 @@ spec:
               echo "    - SECRET_NAME_DATAREFINERY_CHANNEL ...................... ${SECRET_NAME_DATAREFINERY_CHANNEL}"
               echo "    - SECRET_NAME_RABBITMQ_CHANNEL .......................... ${SECRET_NAME_RABBITMQ_CHANNEL}"
               echo "    - SECRET_NAME_ELASTICSEARCH_CHANNEL ..................... ${SECRET_NAME_ELASTICSEARCH_CHANNEL}"
+              echo "    - SECRET_NAME_OPENSEARCH_CHANNEL ........................ ${SECRET_NAME_OPENSEARCH_CHANNEL}"
               echo "    - SECRET_NAME_SPSS_VERSION .............................. ${SECRET_NAME_SPSS_VERSION}"
               echo "    - SECRET_NAME_SPSS_CHANNEL .............................. ${SECRET_NAME_SPSS_CHANNEL}"
               echo "    - SECRET_NAME_CANVASBASE_CHANNEL ........................ ${SECRET_NAME_CANVASBASE_CHANNEL}"
@@ -456,6 +466,7 @@ spec:
               sm_update_secret $SECRET_NAME_DATAREFINERY_CHANNEL "{\"datarefinery_channel\": \"$DATAREFINERY_CHANNEL\" }" "${TAGS}"
               sm_update_secret $SECRET_NAME_RABBITMQ_CHANNEL "{\"opencontent_rabbitmq_channel\": \"$RABBITMQ_CHANNEL\" }" "${TAGS}"
               sm_update_secret $SECRET_NAME_ELASTICSEARCH_CHANNEL "{\"opencontent_elasticsearch_channel\": \"$ELASTICSEARCH_CHANNEL\" }" "${TAGS}"
+              sm_update_secret $SECRET_NAME_OPENSEARCH_CHANNEL "{\"opencontent_opensearch_channel\": \"$OPENSEARCH_CHANNEL\" }" "${TAGS}"
               sm_update_secret $SECRET_NAME_SPSS_VERSION "{\"spss_version\": \"$SPSS_VERSION\" }" "${TAGS}"
               sm_update_secret $SECRET_NAME_SPSS_CHANNEL "{\"spss_channel\": \"$SPSS_CHANNEL\" }" "${TAGS}"
               sm_update_secret $SECRET_NAME_CANVASBASE_CHANNEL "{\"canvasbase_channel\": \"$CANVASBASE_CHANNEL\" }" "${TAGS}"
