update

diff --git a/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml b/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml
--- a/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml
+++ b/instance-applications/101-ibm-sync-jobs-cp4d/templates/02-ibm-cp4d-presync.yaml
@@ -192,15 +192,15 @@ spec:
               echo "================================================================================"
 
               
-              echo 
-              echo "Fetching channel for namespace scope from PackageManifest"
-              echo "================================================================================"
+              # echo 
+              # echo "Fetching channel for namespace scope from PackageManifest"
+              # echo "================================================================================"
 
-              export NAMESPACE_SCOPE_CHANNEL=$((oc get PackageManifest ibm-namespace-scope-operator -n ${CPD_OPERATORS_NAMESPACE} -o json) | jq -r '[.status.channels | .[].name] | last')
-              if [[ -z "${NAMESPACE_SCOPE_CHANNEL}" ]]; then
-                echo "Failed to fetch namespace scope channel"
-                exit 1
-              fi
+              # export NAMESPACE_SCOPE_CHANNEL=$((oc get PackageManifest ibm-namespace-scope-operator -n ${CPD_OPERATORS_NAMESPACE} -o json) | jq -r '[.status.channels | .[].name] | last')
+              # if [[ -z "${NAMESPACE_SCOPE_CHANNEL}" ]]; then
+              #   echo "Failed to fetch namespace scope channel"
+              #   exit 1
+              # fi
 
               echo 
               echo "Fetching values from olm-utils-cm config map"
