Order edge certificate in DRO DNS job

diff --git a/cluster-applications/030-ibm-dro/templates/12-2-dro-dns_job.yaml b/cluster-applications/030-ibm-dro/templates/12-2-dro-dns_job.yaml
--- a/cluster-applications/030-ibm-dro/templates/12-2-dro-dns_job.yaml
+++ b/cluster-applications/030-ibm-dro/templates/12-2-dro-dns_job.yaml
@@ -234,6 +234,23 @@ spec:
 
               fi
 
+              echo ""
+              echo "Ordering edge certificate for ${FULL_RECORD_NAME}..."
+              
+              CERT_ORDER_OUTPUT=$(ibmcloud cis certificate-order "${DOMAIN_ID}" \
+                --hostnames "${FULL_RECORD_NAME}" 2>&1)
+              
+              CERT_ORDER_RC=$?
+              
+              echo "Certificate order output:"
+              echo "${CERT_ORDER_OUTPUT}"
+              
+              if [[ ${CERT_ORDER_RC} -eq 0 ]]; then
+                echo "Edge certificate ordered successfully!"
+              else
+                echo "WARNING: Edge certificate order failed or certificate may already exist"
+              fi
+
       volumes:
         - name: aws
           secret:
