ts

diff --git a/instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml b/instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml
--- a/instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml
+++ b/instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml
@@ -98,6 +98,80 @@ spec:
 
               set -e
 
+              function delete_oc_resource(){
+                RESOURCE=$1
+                NAMESPACE=$2
+                echo
+                echo "------------------------------------------------------------------"
+                echo "Check if resource $RESOURCE is present in namespace $NAMESPACE "
+
+                # don't want a non-zero rc from oc delete to cause the job to fail
+                # so, temporarily set +e
+                set +e
+                RESOURCE_NAME=$(oc get $RESOURCE -n $NAMESPACE -o=jsonpath="{.metadata.name}")
+                set -e
+                if [[ -z "${RESOURCE_NAME}" ]]; then
+                  echo "$RESOURCE not found, skipping"
+                  return 0
+                fi
+
+                echo "oc delete resource $RESOURCE in namespace $NAMESPACE "
+
+                # don't want a non-zero rc from oc delete to cause the job to fail (since we then want to try patching out the finalizers)
+                # so, temporarily set +e
+                set +e
+                oc delete $RESOURCE -n $NAMESPACE --timeout=300s --wait=true
+                return_code=$?
+                set -e
+
+                echo "Verify that resource $RESOURCE is now absent in namespace $NAMESPACE "
+                # don't want a non-zero rc from oc delete to cause the job to fail
+                # so, temporarily set +e
+                set +e
+                RESOURCE_NAME=$(oc get $RESOURCE -n $NAMESPACE -o=jsonpath="{.metadata.name}")
+                set -e
+                if [[ -n "${RESOURCE_NAME}" ]]; then
+                  echo "$RESOURCE still present, failing job"
+                  exit 1
+                fi
+
+                echo "... verified"
+                return 0
+                
+              }
+
+              echo -e "Silently wipe Mongo data"
+
+              # Grab one of the hosts/ports out of docdb master info
+              #export CONFIG=$(echo "${MONGO_INFO}" | sed 's/\\n/\n/g' | sed 's/\\"//g' | /usr/bin/yq '.config')
+              #export CERTIFICATES=$(echo "${MONGO_INFO}" | sed 's/\\n/\n/g' | /usr/bin/yq '.certificates')
+
+              echo ""
+              echo "================================================================================"
+              echo "Settings - wipe_mongo"
+              echo "================================================================================"
+              echo "MAS_INSTANCE_ID ....................... ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"
+              echo "Mongo username ........................ ${COLOR_MAGENTA}${MONGO_USERNAME}"
+              echo "Mongo password ........................ ${COLOR_MAGENTA}${MONGO_PASSWORD:0:6}<snip>"
+              #echo "Mongo config .......................... ${COLOR_MAGENTA}${CONFIG}"
+              echo "Mongo Info ............................ ${COLOR_MAGENTA}${MONGO_INFO}"
+              #echo "Mongo certificates .................... ${COLOR_MAGENTA}${CERTIFICATES}"
+              echo "MAS_WIPE_MONGO_DATA ................... ${COLOR_MAGENTA}${MAS_WIPE_MONGO_DATA}"
+              echo ""
+              echo "================================================================================"
+
+              if [[ "${MAS_WIPE_MONGO_DATA}" == "true" ]]; then
+
+                export ROLE_NAME=wipe_mongo
+                echo "I am in "
+                #ansible-playbook ibm.mas_devops.run_role
+                #rc=$?
+                #echo "Role wipe_mongo completes with rc=${rc}"
+                #[ $rc -ne 0 ] && exit $rc
+              fi
+
+              #delete_oc_resource "${CR_KIND}.${CR_API_VERSION}/${CR_NAME}" "${CR_NAMESPACE}"
+
 
       restartPolicy: Never
       serviceAccountName: {{ $sa_name }}
