configure wsl and small changes in cp4d

diff --git a/instance-applications/090-ibm-wsl/templates/04-ibm-wsl-post-verify.yaml b/instance-applications/090-ibm-wsl/templates/04-ibm-wsl-post-verify.yaml
--- a/instance-applications/090-ibm-wsl/templates/04-ibm-wsl-post-verify.yaml
+++ b/instance-applications/090-ibm-wsl/templates/04-ibm-wsl-post-verify.yaml
@@ -46,6 +46,7 @@ spec:
               set -e
               echo
               echo "================================================================================"
+              echo "Part A - Waiting for WSL and its dependencies to be complete"
               echo "Wait for CCS Cr to be ready and patch if needed"
               echo "================================================================================"
               echo
@@ -71,9 +72,9 @@ spec:
               done
 
               echo "Patching CCS ccs-cr if not already patched"
-              CCS_COUCHDB_RES=$(oc get CCS ccs-cr -n ${CPD_INSTANCE_NAMESPACE} --ignore-not-found -ojsonpath='{.spec.couchdb_resources}')
-              CCS_BLOCKSTORAGE=$(oc get CCS ccs-cr -n ${CPD_INSTANCE_NAMESPACE} --ignore-not-found -ojsonpath='{.spec.blockStorageClass}')
-              CCS_IMAGEPULLSECRET=$(oc get CCS ccs-cr -n ${CPD_INSTANCE_NAMESPACE} --ignore-not-found -ojsonpath='{.spec.imagePullSecret}')
+              CCS_COUCHDB_RES=$(oc get CCS ccs-cr -n ${CPD_INSTANCE_NAMESPACE} -ojsonpath='{.spec.couchdb_resources}')
+              CCS_BLOCKSTORAGE=$(oc get CCS ccs-cr -n ${CPD_INSTANCE_NAMESPACE} -ojsonpath='{.spec.blockStorageClass}')
+              CCS_IMAGEPULLSECRET=$(oc get CCS ccs-cr -n ${CPD_INSTANCE_NAMESPACE} -ojsonpath='{.spec.imagePullSecret}')
 
               if [[ -z $CCS_COUCHDB_RES || -z $CCS_BLOCKSTORAGE || -z $CCS_IMAGEPULLSECRET ]]; then
                 echo "CCS CR needs to be patched"
@@ -131,20 +132,18 @@ spec:
               done
 
               echo "Patching ElasticsearchCluster elasticsearch-master if not already patched"
-              while true; do
-                ELASTICSEARCH_IMAGEPULLSECRET=$(oc get ElasticsearchCluster elasticsearch-master -n ${CPD_INSTANCE_NAMESPACE} --ignore-not-found -ojsonpath='{.spec.imagePullSecret}')
+             
+              ELASTICSEARCH_IMAGEPULLSECRET=$(oc get ElasticsearchCluster elasticsearch-master -n ${CPD_INSTANCE_NAMESPACE} -ojsonpath='{.spec.imagePullSecret}')
 
-                if [[ -z $ELASTICSEARCH_IMAGEPULLSECRET ]]; then
-                  echo "elasticsearch-master needs to be patched"
-                  echo "patching elasticsearch-master and forcing reconcile..."
-                  oc scale deployment ibm-elasticsearch-operator-ibm-es-controller-manager -n ${CPD_OPERATORS_NAMESPACE} --replicas=0
-                  oc delete Job elasticsearch-master-ibm-elasticsearch-create-snapshot-repo-job -n ${CPD_INSTANCE_NAMESPACE} --ignore-not-found
-                  oc delete StatefulSet -n ${CPD_INSTANCE_NAMESPACE} --selector="app.kubernetes.io/instance=elasticsearch-master --ignore-not-found"
-                  oc patch --type='merge' ElasticsearchCluster elasticsearch-master -n ${CPD_INSTANCE_NAMESPACE} -p "{\"spec\":{ \"imagePullSecret\":\"ibm-entitlement-key\"}}"
-                  oc scale deployment ibm-elasticsearch-operator-ibm-es-controller-manager -n ${CPD_OPERATORS_NAMESPACE} --replicas=1
-                  break
-                fi
-              done
+              if [[ -z $ELASTICSEARCH_IMAGEPULLSECRET ]]; then
+                echo "elasticsearch-master needs to be patched"
+                echo "patching elasticsearch-master and forcing reconcile..."
+                oc scale deployment ibm-elasticsearch-operator-ibm-es-controller-manager -n ${CPD_OPERATORS_NAMESPACE} --replicas=0
+                oc delete Job elasticsearch-master-ibm-elasticsearch-create-snapshot-repo-job -n ${CPD_INSTANCE_NAMESPACE} --ignore-not-found
+                oc delete StatefulSet -n ${CPD_INSTANCE_NAMESPACE} --selector="app.kubernetes.io/instance=elasticsearch-master --ignore-not-found"
+                oc patch --type='merge' ElasticsearchCluster elasticsearch-master -n ${CPD_INSTANCE_NAMESPACE} -p "{\"spec\":{ \"imagePullSecret\":\"ibm-entitlement-key\"}}"
+                oc scale deployment ibm-elasticsearch-operator-ibm-es-controller-manager -n ${CPD_OPERATORS_NAMESPACE} --replicas=1
+              fi
 
               echo
               echo "Waiting for ibm-elasticsearch-operator to be ready again..."
@@ -152,7 +151,7 @@ spec:
               wait_period=0
               while true; do
                 wait_period=$(($wait_period+60))
-                if [ $wait_period -gt 1200 ];then
+                if [ $wait_period -gt 1200 ]; then
                   echo "Elasticsearch operator is not ready after 20 minutes of waiting. exiting..."
                   exit 1
                 else
@@ -176,7 +175,7 @@ spec:
               wait_period=0
               while true; do
                 wait_period=$(($wait_period+300))
-                if [ $wait_period -gt 15000 ];then
+                if [ $wait_period -gt 15000 ]; then
                   echo "ccsStatus is not complete after 4 hours and 10 minutes of waiting. Exiting..."
                   exit 1
                 else
@@ -202,22 +201,27 @@ spec:
               wait_period=0
               while true; do
                 wait_period=$(($wait_period+5))
-                if [ $wait_period -gt 600 ];then
+                if [ $wait_period -gt 600 ]; then
                   echo "notebookruntimes.ws.cpd.ibm.com CRD is not avalable after 10 minutes of waiting. Exiting..."
                   exit 1
                 else
                   sleep 5
                 fi
 
-                WS_LOOKUP=$(oc get CustomResourceDefinition notebookruntimes.ws.cpd.ibm.com --ignore-not-found)
-                if [[ ! -z ${WS_LOOKUP} ]]; then
+                WSR_LOOKUP=$(oc get CustomResourceDefinition notebookruntimes.ws.cpd.ibm.com --ignore-not-found)
+                if [[ ! -z ${WSR_LOOKUP} ]]; then
                   echo "notebookruntimes.ws.cpd.ibm.com is available"
                   break
                 fi
               done
 
+              echo
+              echo "================================================================================"
+              echo "to be continued in job part B..."
+              echo              
+
       restartPolicy: Never
-      serviceAccountName: presync-cpd-prereq-sa
+      serviceAccountName: wsl-precheck-sa
   backoffLimit: 4
 
 
@@ -244,7 +248,7 @@ spec:
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: "cpd-wsl-post-verify-job-part b"
+  name: "cpd-wsl-post-verify-job-part-b"
   namespace: "{{ .Values.cpd_operators_namespace }}"
   annotations:
     argocd.argoproj.io/sync-wave: "098"
@@ -274,12 +278,12 @@ spec:
           env:
             - name: CPD_INSTANCE_NAMESPACE
               value: {{ .Values.cpd_instance_namespace }}
-            - name: CPD_OPERATORS_NAMESPACE
-              value: {{ .Values.cpd_operators_namespace }}
-            - name: CPD_SERVICE_STORAGE_CLASS
-              value: {{ .Values.cpd_service_storage_class }}
-            - name: CPD_SERVICE_BLOCK_STORAGE_CLASS
-              value: {{ .Values.cpd_service_block_storage_class }}
+            - name: MAS_CONFIG_DIR
+              value: {{ .Values.mas_config_dir }}
+            - name: INSTANCE_ID
+              value: {{ .Values.instance_id }}
+            - name: CPD_WSL_PROJECT_NAME
+              value: {{ .values.cpd_wsl_project_name }}
           command:
             - /bin/sh
             - -c
@@ -288,6 +292,7 @@ spec:
               set -e
               echo
               echo "================================================================================"
+              echo "Part B - Waiting for WSL and its dependencies to be complete"
               echo "Wait for WS Status to be Completed"
               echo "================================================================================"
               echo
@@ -297,7 +302,7 @@ spec:
               wait_period=0
               while true; do
                 wait_period=$(($wait_period+300))
-                if [ $wait_period -gt 9000 ];then
+                if [ $wait_period -gt 9000 ]; then
                   echo "wsStatus is not complete after 2 hours and 30 minutes of waiting."
                   echo "Watson Studio install failed (wsStatus). Exiting..."
                   exit 1
@@ -312,6 +317,61 @@ spec:
                 fi
               done
 
+
+              echo
+              echo "================================================================================"
+              echo "Lookup Cloud Pak for Data admin username"
+              echo "================================================================================"
+              USERNAME=$(oc get secret ibm-iam-bindinfo-platform-auth-idp-credentials -n ${CPD_INSTANCE_NAMESPACE} --ignore-not-found -o json | jq -r '.data.admin_username' | base64 -d)
+
+              if [[ -z ${USERNAME} ]]; then
+                export CPD_ADMIN_USERNAME="admin"
+                export SECRET_NAME="admin-user-details"
+                export ADMIN_PASSWORD_PROPERTY="initial_admin_password"
+
+              else
+                export CPD_ADMIN_USERNAME="cpadmin"
+                export SECRET_NAME="ibm-iam-bindinfo-platform-auth-idp-credentials"
+                export ADMIN_PASSWORD_PROPERTY="admin_password"
+              fi
+              
+              
+              echo
+              echo "Lookup Cloud Pak for Data admin password"
+              CPD_ADMIN_PASSWORD=$(oc get secret $SECRET_NAME -n ${CPD_INSTANCE_NAMESPACE} -o json | jq -r ".data.${ADMIN_PASSWORD_PROPERTY}" | base64 -d)
+
+              echo
+              echo "Lookup Cloud Pak for Data admin url"
+              CPD_ADMIN_URL=$(oc get ZenService lite-cr -o jsonpath="{.status.url}{'\n'}" -n ${CPD_INSTANCE_NAMESPACE})
+
+              if [[ -z ${CPD_ADMIN_URL} || -z ${CPD_ADMIN_USERNAME} || -z ${CPD_ADMIN_PASSWORD} ]]; then
+                echo "CPD admin username/password/url details are missing, please check your Cloud Pak For Data instance health!"
+                exit 1
+              fi
+
+              echo
+              echo
+              echo "================================================================================"
+              echo "Debug Cloud Pak for Data Admin details"
+              echo "================================================================================"
+              echo "- CP4D Dashboard ......................... ${CPD_ADMIN_URL}"
+              echo "- CP4D Admin Username .................... ${CPD_ADMIN_USERNAME}"
+              echo "- CP4D Admin Password .................... ${CPD_ADMIN_PASSWORD:0:2}<snip>"
+
+              echo
+              echo "================================================================================"
+              echo "Generate MAS Config into $MAS_CONFIG_DIR folder"
+              echo "================================================================================"
+              echo "- CP4D WSL Project Name .................. ${CPD_WSL_PROJECT_NAME}"
+              echo "- MAS Config Directory ................... ${MAS_CONFIG_DIR}"
+
+              echo "Authorize CP4D Admin and get bearer token"
+              CPD_BEARER_TOKEN=$(curl -X POST --location "${CPD_ADMIN_URL}/icp4d-api/v1/authorize" --header "Cache-Control:no-cache" --header "Content-Type:application/json" --data "{\"username\":\"$CPD_ADMIN_USERNAME\",\"password\":\"$CPD_ADMIN_PASSWORD\"}")
+              # WSL_PROJECT_ID=$(curl -X GET --location "${CPD_ADMIN_URL}/v2/projects" --header "Authorization:Bearer ${CPD_BEARER_TOKEN}" --header "Cache-Control:no-cache" --header "Content-Type:application/json" --data "{\"username\":\"$CPD_ADMIN_USERNAME\",\"password\":\"$CPD_ADMIN_PASSWORD\"}")
+              echo "${CPD_BEARER_TOKEN}"
+
+
+
       restartPolicy: Never
-      serviceAccountName: presync-cpd-prereq-sa
+      serviceAccountName: wsl-precheck-sa
   backoffLimit: 4
