update script

diff --git a/cluster-applications/200-cluster-promotion/templates/03-cluster-promoter_Job.yaml b/cluster-applications/200-cluster-promotion/templates/03-cluster-promoter_Job.yaml
--- a/cluster-applications/200-cluster-promotion/templates/03-cluster-promoter_Job.yaml
+++ b/cluster-applications/200-cluster-promotion/templates/03-cluster-promoter_Job.yaml
@@ -128,6 +128,8 @@ spec:
                 interval=30
                 index=0
                 while true; do
+                  # This section might fail if remote branch doesn't exist
+                  set +e
                   echo "git: fetch origin $TARGET_GIT_BRANCH"
                   git fetch origin $TARGET_GIT_BRANCH
 
@@ -136,6 +138,7 @@ spec:
 
                   echo "git: pull origin $TARGET_GIT_BRANCH --rebase"
                   git pull origin $TARGET_GIT_BRANCH --rebase
+                  set -e
 
                   echo "git: Pushing changes to branch $TARGET_GIT_BRANCH"
                   git push -u origin $TARGET_GIT_BRANCH
