fix

diff --git a/applications/ibm-mas-system-config-cleanup/templates/00-postsync-delete-cfg-crs_Job.yaml b/applications/ibm-mas-system-config-cleanup/templates/00-postsync-delete-cfg-crs_Job.yaml
--- a/applications/ibm-mas-system-config-cleanup/templates/00-postsync-delete-cfg-crs_Job.yaml
+++ b/applications/ibm-mas-system-config-cleanup/templates/00-postsync-delete-cfg-crs_Job.yaml
@@ -89,7 +89,12 @@ spec:
                 NAMESPACE=$2
                 echo
                 echo " Check if resource $RESOURCE is present in namepsace $NAMESPACE "
+
+                # don't want a non-zero rc from oc delete to cause the job to fail
+                # so, temporarily set +e
+                set +e
                 RESOURCE_NAME=$(oc get $RESOURCE -n $NAMESPACE -o=jsonpath="{.metadata.name}")
+                set -e
                 if [ -z "${RESOURCE_NAME}" ]]; then
                   echo "$RESOURCE not found, skipping"
                 fi
@@ -112,7 +117,11 @@ spec:
                 fi
 
                 echo "Verify that resource $RESOURCE is now absent in namepsace $NAMESPACE "
+                # don't want a non-zero rc from oc delete to cause the job to fail
+                # so, temporarily set +e
+                set +e
                 RESOURCE_NAME=$(oc get $RESOURCE -n $NAMESPACE -o=jsonpath="{.metadata.name}")
+                set -e
                 if [ -n "${RESOURCE_NAME}" ]]; then
                   echo "$RESOURCE still present, failing job"
                   exit 1
