update

diff --git a/instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml b/instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
--- a/instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
+++ b/instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
@@ -440,8 +440,8 @@ spec:
                       fi
                       version_sync_count=$((version_sync_count+1))
                       if [ $version_sync_count -gt 60 ]; then
-                        echo "WARNING: Timeout waiting for db2uinstance spec.version, status.version, and status.state=Ready after 600s. Proceeding anyway."
-                        break
+                        echo "ERROR: Timeout waiting for db2uinstance spec.version, status.version, and status.state=Ready after 600s."
+                        exit 1
                       fi
                       sleep 10
                     done
