indentation

diff --git a/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml b/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml
--- a/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml
+++ b/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml
@@ -416,40 +416,40 @@ spec:
                   fi
 
                   if [[ $(( `date +%Y%m%d` - ${timestamp:0:8} )) -lt 2 || -z ${timestamp} ]]; then
-                  # check if it is a full backup
-                  BACKUP_TYPE_SCRIPT='/tmp/backup_type_script.sh'
+                    # check if it is a full backup
+                    BACKUP_TYPE_SCRIPT='/tmp/backup_type_script.sh'
 
-                  cat > ${BACKUP_TYPE_SCRIPT} << EOF
-                    #!/bin/bash
-                    db2 connect to ${DB2_DBNAME};
-                    if [ \$? != 0 ]; then
-                      echo "Failed to connect to database!"
-                      exit 1
-                    fi
-                    backup_type=\$(db2 -x "select OPERATIONTYPE from sysibmadm.db_history where OPERATION='B' and START_TIME=${timestamp}")
-                    echo "Backup type is \${backup_type}"
+                    cat > ${BACKUP_TYPE_SCRIPT} << EOF
+                      #!/bin/bash
+                      db2 connect to ${DB2_DBNAME};
+                      if [ \$? != 0 ]; then
+                        echo "Failed to connect to database!"
+                        exit 1
+                      fi
+                      backup_type=\$(db2 -x "select OPERATIONTYPE from sysibmadm.db_history where OPERATION='B' and START_TIME=${timestamp}")
+                      echo "Backup type is \${backup_type}"
 
               EOF
 
-                  chmod +x ${BACKUP_TYPE_SCRIPT}
-                  echo ""
-                  echo "Copy ${BACKUP_TYPE_SCRIPT} to ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0"
-                  echo "--------------------------------------------------------------------------------"
-                  oc cp ${BACKUP_TYPE_SCRIPT} ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0:${BACKUP_TYPE_SCRIPT} -c db2u || exit $?
+                    chmod +x ${BACKUP_TYPE_SCRIPT}
+                    echo ""
+                    echo "Copy ${BACKUP_TYPE_SCRIPT} to ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0"
+                    echo "--------------------------------------------------------------------------------"
+                    oc cp ${BACKUP_TYPE_SCRIPT} ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0:${BACKUP_TYPE_SCRIPT} -c db2u || exit $?
 
-                  echo ""
-                  echo "Executing ${BACKUP_TYPE_SCRIPT} file on ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0"
-                  echo "--------------------------------------------------------------------------------"
-                  oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "${BACKUP_TYPE_SCRIPT} | tee /tmp/backuptype.log" db2inst1 || exit $?
-                  backup_type=`oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "cat /tmp/backuptype.log | grep 'Backup type is'" db2inst1`
-                  backup_type=`echo ${backup_type} | tr -d '' | awk '{print $NF}'`
-                  echo "Backup type is ${backup_type}"
-                  if [[ $backup_type == 'F' || $backup_type == 'N' ]]; then
-                    echo "The latest backup ${timestamp} is full backup"
-                  else
-                    echo "The latest backup ${timestamp} is not a full backup"
-                    timestamp=''
-                  fi
+                    echo ""
+                    echo "Executing ${BACKUP_TYPE_SCRIPT} file on ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0"
+                    echo "--------------------------------------------------------------------------------"
+                    oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "${BACKUP_TYPE_SCRIPT} | tee /tmp/backuptype.log" db2inst1 || exit $?
+                    backup_type=`oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "cat /tmp/backuptype.log | grep 'Backup type is'" db2inst1`
+                    backup_type=`echo ${backup_type} | tr -d '' | awk '{print $NF}'`
+                    echo "Backup type is ${backup_type}"
+                    if [[ $backup_type == 'F' || $backup_type == 'N' ]]; then
+                      echo "The latest backup ${timestamp} is full backup"
+                    else
+                      echo "The latest backup ${timestamp} is not a full backup"
+                      timestamp=''
+                    fi
                   fi
                 fi
 
