Testing

diff --git a/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml b/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml
--- a/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml
+++ b/instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml
@@ -321,7 +321,6 @@ spec:
               if [[ ! ($PRIMARY_ROLE == 'PRIMARY' && $STANDBY_ROLE == 'STANDBY') ]]; then
                 echo "Checking if a backup already exists on ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0"
                 is_backup_log_available=`oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "if [ -f /mnt/backup/standby/dbbackup.log ]; then echo 'true'; else echo 'false'; fi"`
-                echo "is_backup_log_available - $is_backup_log_available"
                 if [[ $is_backup_log_available == 'true' ]]; then
                   timestamp=`oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "cat /mnt/backup/standby/dbbackup.log | grep 'timestamp' | rev | cut -d ' ' -f1 | rev" db2inst1`
                   echo "timestamp - $timestamp"
@@ -329,11 +328,9 @@ spec:
                   echo "backup_filename - $backup_filename"
                   if [[ ${timestamp:0:8} == `date +%Y%m%d` ]]; then
                     is_backup_file_available=`oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "if [ -f /mnt/backup/standby/$backup_filename ]; then echo 'true'; else echo 'false'; fi"`
-                    echo "is_backup_file_available - $is_backup_file_available"
                   fi
                 fi
 
-                echo "is_backup_file_available - $is_backup_file_available"
                 if [[ $is_backup_file_available == 'false' ]]; then
                   echo ""
                   echo "Taking backup on ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0"
@@ -345,17 +342,23 @@ spec:
 
                   backup_filename=`oc exec -n ${DB2_NAMESPACE} c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 -- su -lc "ls /mnt/backup/standby | grep ${timestamp}" db2inst1`
                   echo "Backup filename is ${backup_filename}"
+                else
+                  echo "Backup is already available in primary. Hence skipping"
                 fi
 
                 echo "Checking if backup file was copied already to standby c-${DB2_INSTANCE_NAME}-db2u-0"
                 is_backup_copied=`oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc "if [ -f /tmp/${backup_filename} ]; then echo 'true'; else echo 'false'; fi"`
-                echo $is_backup_copied
                 if [[ $is_backup_copied == 'true' ]]; then
-                  echo "Validating the copied backup image"
+                  echo "Earlier copied backup is available in standby. Validating the backup file"
                   rc=0
-                  oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc "db2ckbkp -H /tmp/${backup_filename}; exit 1;" db2inst1 || rc=$?
+                  bkp_validation=`oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc "db2ckbkp -h /tmp/${backup_filename}; exit 1;" db2inst1`
+                  echo $bkp_validation
+                  if [[ echo $bkp_validation | grep 'ERROR' ]]; then
+                    rc=1
+                  fi
                   echo $rc
                 fi
+                echo $rc
                 if [[ $rc != 0 || $is_backup_copied == 'false' ]]; then
                   echo ""
                   echo "Copying backup /mnt/backup/standby/${backup_filename} from ${DB2_NAMESPACE}/c-${PRIMARY_DB2_INSTANCE_NAME}-db2u-0 to ${DB2_NAMESPACE}/c-${DB2_INSTANCE_NAME}-db2u-0 "
