updates for spark

diff --git a/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml b/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
--- a/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
+++ b/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
@@ -195,6 +195,22 @@ spec:
               fi
       
               echo
+              echo "Fetching IBM Analytics Engine Powered by Apache Spark Version..."
+              export SPARK_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.analyticsengine.cr_version')
+              if [[ -z "${SPARK_VERSION}" ]]; then
+                echo "Failed to fetch IBM Analytics Engine Powered by Apache Spark version"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching IBM Analytics Engine Powered by Apache Spark Channel..."
+              export SPARK_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.analyticsengine.sub_channel')
+              if [[ -z "${SPARK_CHANNEL}" ]]; then
+                echo "Failed to fetch IBM Analytics Engine Powered by Apache Spark channel"
+                exit 1
+              fi
+            
+              echo
               echo "Fetching Watson Studio Version..."
               export WSL_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.ws.cr_version')
               if [[ -z "${WSL_VERSION}" ]]; then
@@ -285,6 +301,8 @@ spec:
               SECRET_NAME_CPD_PLATFORM_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/cpd_platform_channel
               SECRET_NAME_WML_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wml_version
               SECRET_NAME_WML_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wml_channel
+              SECRET_NAME_SPARK_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spark_version
+              SECRET_NAME_SPARK_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spark_channel
               SECRET_NAME_WSL_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wsl_version
               SECRET_NAME_WSL_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wsl_channel
               SECRET_NAME_CCS_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/ccs_version
@@ -314,6 +332,8 @@ spec:
               echo "    - SECRET_NAME_CPD_PLATFORM_CHANNEL ...................... ${SECRET_NAME_CPD_PLATFORM_CHANNEL}"
               echo "    - SECRET_NAME_WML_VERSION ............................... ${SECRET_NAME_WML_VERSION}"
               echo "    - SECRET_NAME_WML_CHANNEL ............................... ${SECRET_NAME_WML_CHANNEL}"
+              echo "    - SECRET_NAME_SPARK_VERSION ............................. ${SECRET_NAME_SPARK_VERSION}"
+              echo "    - SECRET_NAME_SPARK_CHANNEL ............................. ${SECRET_NAME_SPARK_CHANNEL}"
               echo "    - SECRET_NAME_WSL_VERSION ............................... ${SECRET_NAME_WSL_VERSION}"
               echo "    - SECRET_NAME_WSL_CHANNEL ............................... ${SECRET_NAME_WSL_CHANNEL}"
               echo "    - SECRET_NAME_CCS_VERSION ............................... ${SECRET_NAME_CCS_VERSION}"
@@ -333,7 +353,9 @@ spec:
               sm_update_secret $SECRET_NAME_CPFS_CHANNEL "{\"cpfs_channel\": \"$CPFS_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_CPD_PLATFORM_CHANNEL "{\"cpd_platform_channel\": \"$CPD_PLATFORM_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_WML_VERSION "{\"wml_version\": \"$WML_VERSION\" }"
-              sm_update_secret $SECRET_NAME_WML_CHANNEL "{\"wml_channel\": \"$WML_CHANNEL\" }"
+              sm_update_secret $SECRET_NAME_WML_CHANNEL "{\"wml_channel\": \"$WML_CHANNEL\" }"              
+              sm_update_secret $SECRET_NAME_SPARK_VERSION "{\"spark_version\": \"$SPARK_VERSION\" }"
+              sm_update_secret $SECRET_NAME_SPARK_CHANNEL "{\"spark_channel\": \"$SPARK_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_WSL_VERSION "{\"wsl_version\": \"$WSL_VERSION\" }"
               sm_update_secret $SECRET_NAME_WSL_CHANNEL "{\"wsl_channel\": \"$WSL_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_CCS_VERSION "{\"ccs_version\": \"$CCS_VERSION\" }"
