Version 2 updates (#172)

diff --git a/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml b/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
--- a/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
+++ b/instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
@@ -35,6 +35,7 @@ rules:
       - packagemanifests
   - verbs:
       - get
+      - create
     apiGroups:
       - ''
     resources:
@@ -68,7 +69,8 @@ metadata:
   # This is to ensure that ArgoCD will delete and recreate the job if (and only if) anything changes
   # Any change to cluster config will trigger a rerun of the job.
   # The job is idempotent and quick so no real harm in running it when we don't actually need to.
-  name: "presync-cpd-olm-job-{{ .Values | toYaml | adler32sum }}"
+  # The v1 in the name allows use to change this if there is a modification needed that is not in the yaml
+  name: "presync-cpd-olm-job-v1-{{ .Values | toYaml | adler32sum }}"
   namespace: mas-{{ .Values.instance_id }}-syncres
   annotations:
     argocd.argoproj.io/sync-wave: "003"
@@ -86,7 +88,7 @@ spec:
     spec:
       containers:
         - name: run
-          image: quay.io/ibmmas/cli:9.4.0-pre.gitops
+          image: quay.io/ibmmas/cli:latest
           imagePullPolicy: IfNotPresent
           resources:
             limits:
@@ -147,7 +149,7 @@ spec:
               echo "Fetching values from olm-utils-cm config map"
               echo "================================================================================"
               echo "Fetching IBM Licensing Channel..."
-              export LICENSING_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.["ibm-licensing"].sub_channel')
+              export LICENSING_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.["ibm-licensing"].sub_channel')
               if [[ -z "${LICENSING_CHANNEL}" ]]; then
                 echo "Failed to fetch ibm licensing channel"
                 exit 1
@@ -155,7 +157,7 @@ spec:
 
               echo
               echo "Fetching IBM Licensing Version..."
-              export LICENSING_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.["ibm-licensing"].csv_version')
+              export LICENSING_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.["ibm-licensing"].csv_version')
               if [[ -z "${LICENSING_VERSION}" ]]; then
                 echo "Failed to fetch ibm licensing version"
                 exit 1
@@ -163,7 +165,7 @@ spec:
 
               echo
               echo "Fetching CPFS Channel..."
-              export CPFS_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.cpfs.sub_channel')
+              export CPFS_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.cpfs.sub_channel')
               if [[ -z "${CPFS_CHANNEL}" ]]; then
                 echo "Failed to fetch cpfs channel"
                 exit 1
@@ -171,15 +173,47 @@ spec:
 
               echo
               echo "Fetching CPD Platform Channel..."
-              export CPD_PLATFORM_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.cpd_platform.sub_channel')
+              export CPD_PLATFORM_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.cpd_platform.sub_channel')
               if [[ -z "${CPD_PLATFORM_CHANNEL}" ]]; then
                 echo "Failed to fetch cpd platform channel"
                 exit 1
               fi
 
               echo
+              echo "Fetching Watson Machine Learning Version..."
+              export WML_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.wml.cr_version')
+              if [[ -z "${WML_VERSION}" ]]; then
+                echo "Failed to fetch watson machine learning version"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching Watson Machine Learning Channel..."
+              export WML_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.wml.sub_channel')
+              if [[ -z "${WML_CHANNEL}" ]]; then
+                echo "Failed to fetch watson machine learning channel"
+                exit 1
+              fi
+      
+              echo
+              echo "Fetching IBM Analytics Engine Powered by Apache Spark Version..."
+              export SPARK_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.analyticsengine.cr_version')
+              if [[ -z "${SPARK_VERSION}" ]]; then
+                echo "Failed to fetch IBM Analytics Engine Powered by Apache Spark version"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching IBM Analytics Engine Powered by Apache Spark Channel..."
+              export SPARK_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.analyticsengine.sub_channel')
+              if [[ -z "${SPARK_CHANNEL}" ]]; then
+                echo "Failed to fetch IBM Analytics Engine Powered by Apache Spark channel"
+                exit 1
+              fi
+            
+              echo
               echo "Fetching Watson Studio Version..."
-              export WSL_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.ws.cr_version')
+              export WSL_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.ws.cr_version')
               if [[ -z "${WSL_VERSION}" ]]; then
                 echo "Failed to fetch watson studio version"
                 exit 1
@@ -187,7 +221,7 @@ spec:
 
               echo
               echo "Fetching Watson Studio Channel..."
-              export WSL_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.ws.sub_channel')
+              export WSL_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.ws.sub_channel')
               if [[ -z "${WSL_CHANNEL}" ]]; then
                 echo "Failed to fetch watson studio channel"
                 exit 1
@@ -195,7 +229,7 @@ spec:
 
               echo
               echo "Fetching CCS Version..."
-              export CCS_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.ccs.cr_version')
+              export CCS_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.ccs.cr_version')
               if [[ -z "${CCS_VERSION}" ]]; then
                 echo "Failed to fetch ccs version"
                 exit 1
@@ -203,7 +237,7 @@ spec:
 
               echo
               echo "Fetching CCS Channel..."
-              export CCS_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.ccs.sub_channel')
+              export CCS_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.ccs.sub_channel')
               if [[ -z "${CCS_CHANNEL}" ]]; then
                 echo "Failed to fetch ccs channel"
                 exit 1
@@ -211,7 +245,7 @@ spec:
 
               echo
               echo "Fetching Watson Studio Runtimes Version..."
-              export WS_RUNTIMES_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.ws_runtimes.cr_version')
+              export WS_RUNTIMES_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.ws_runtimes.cr_version')
               if [[ -z "${WS_RUNTIMES_VERSION}" ]]; then
                 echo "Failed to fetch watson studio runtimes version"
                 exit 1
@@ -219,7 +253,7 @@ spec:
 
               echo
               echo "Fetching Watson Studio Runtimes Channel..."
-              export WS_RUNTIMES_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.ws_runtimes.sub_channel')
+              export WS_RUNTIMES_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.ws_runtimes.sub_channel')
               if [[ -z "${WS_RUNTIMES_CHANNEL}" ]]; then
                 echo "Failed to fetch watson studio runtimes channel"
                 exit 1
@@ -227,7 +261,7 @@ spec:
 
               echo
               echo "Fetching DataRefinery Version..."
-              export DATAREFINERY_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.datarefinery.cr_version')
+              export DATAREFINERY_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.datarefinery.cr_version')
               if [[ -z "${DATAREFINERY_VERSION}" ]]; then
                 echo "Failed to fetch datarefinery version"
                 exit 1
@@ -235,7 +269,7 @@ spec:
 
               echo
               echo "Fetching DataRefinery Channel..."
-              export DATAREFINERY_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.datarefinery.sub_channel')
+              export DATAREFINERY_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.datarefinery.sub_channel')
               if [[ -z "${DATAREFINERY_CHANNEL}" ]]; then
                 echo "Failed to fetch datarefinery channel"
                 exit 1
@@ -243,7 +277,7 @@ spec:
 
               echo
               echo "Fetching Opencontent Rabbitmq Channel..."
-              export RABBITMQ_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.opencontent_rabbitmq.sub_channel')
+              export RABBITMQ_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.opencontent_rabbitmq.sub_channel')
               if [[ -z "${RABBITMQ_CHANNEL}" ]]; then
                 echo "Failed to fetch opencontent rabbitmq channel"
                 exit 1
@@ -251,9 +285,49 @@ spec:
 
               echo
               echo "Fetching Opencontent Elasticsearch Channel..."
-              export ELASTICSEARCH_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq -r '.data.release_components_meta' | yq -r '.opencontent_elasticsearch.sub_channel')
+              export ELASTICSEARCH_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.opencontent_elasticsearch.sub_channel')
               if [[ -z "${ELASTICSEARCH_CHANNEL}" ]]; then
                 echo "Failed to fetch opencontent elasticsearch channel"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching AI Openscale Channel..."
+              export AIOPENSCALE_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.openscale.sub_channel')
+              if [[ -z "${AIOPENSCALE_CHANNEL}" ]]; then
+                echo "Failed to fetch aiopenscale channel"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching AI Openscale Version..."
+              export AIOPENSCALE_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.openscale.cr_version')
+              if [[ -z "${AIOPENSCALE_VERSION}" ]]; then
+                echo "Failed to fetch aiopenscale version"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching SPSS Version..."
+              export SPSS_VERSION=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.spss.cr_version')
+              if [[ -z "${SPSS_VERSION}" ]]; then
+                echo "Failed to fetch SPSS version"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching SPSS Channel..."
+              export SPSS_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.spss.sub_channel')
+              if [[ -z "${SPSS_CHANNEL}" ]]; then
+                echo "Failed to fetch SPSS channel"
+                exit 1
+              fi
+
+              echo
+              echo "Fetching Canvasbase Channel..."
+              export CANVASBASE_CHANNEL=$((oc get ConfigMap olm-utils-cm -o json) | yq '.data.release_components_meta' | yq '.canvasbase.sub_channel')
+              if [[ -z "${CANVASBASE_CHANNEL}" ]]; then
+                echo "Failed to fetch Canvasbase channel"
                 exit 1
               fi
 
@@ -266,6 +340,10 @@ spec:
               SECRET_NAME_LICENSING_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/licensing_version
               SECRET_NAME_CPFS_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/cpfs_channel
               SECRET_NAME_CPD_PLATFORM_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/cpd_platform_channel
+              SECRET_NAME_WML_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wml_version
+              SECRET_NAME_WML_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wml_channel
+              SECRET_NAME_SPARK_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spark_version
+              SECRET_NAME_SPARK_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spark_channel
               SECRET_NAME_WSL_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wsl_version
               SECRET_NAME_WSL_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/wsl_channel
               SECRET_NAME_CCS_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/ccs_version
@@ -276,6 +354,11 @@ spec:
               SECRET_NAME_DATAREFINERY_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/datarefinery_channel
               SECRET_NAME_RABBITMQ_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/opencontent_rabbitmq_channel
               SECRET_NAME_ELASTICSEARCH_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/opencontent_elasticsearch_channel
+              SECRET_NAME_AIOPENSCALE_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/aiopenscale_version
+              SECRET_NAME_AIOPENSCALE_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/aiopenscale_channel
+              SECRET_NAME_SPSS_VERSION=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spss_version
+              SECRET_NAME_SPSS_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/spss_channel
+              SECRET_NAME_CANVASBASE_CHANNEL=${ACCOUNT_ID}/${CLUSTER_ID}/${INSTANCE_ID}/canvasbase_channel
 
               echo
               echo 
@@ -293,6 +376,10 @@ spec:
               echo "    - SECRET_NAME_LICENSING_VERSION ......................... ${SECRET_NAME_LICENSING_VERSION}"
               echo "    - SECRET_NAME_CPFS_CHANNEL .............................. ${SECRET_NAME_CPFS_CHANNEL}"
               echo "    - SECRET_NAME_CPD_PLATFORM_CHANNEL ...................... ${SECRET_NAME_CPD_PLATFORM_CHANNEL}"
+              echo "    - SECRET_NAME_WML_VERSION ............................... ${SECRET_NAME_WML_VERSION}"
+              echo "    - SECRET_NAME_WML_CHANNEL ............................... ${SECRET_NAME_WML_CHANNEL}"
+              echo "    - SECRET_NAME_SPARK_VERSION ............................. ${SECRET_NAME_SPARK_VERSION}"
+              echo "    - SECRET_NAME_SPARK_CHANNEL ............................. ${SECRET_NAME_SPARK_CHANNEL}"
               echo "    - SECRET_NAME_WSL_VERSION ............................... ${SECRET_NAME_WSL_VERSION}"
               echo "    - SECRET_NAME_WSL_CHANNEL ............................... ${SECRET_NAME_WSL_CHANNEL}"
               echo "    - SECRET_NAME_CCS_VERSION ............................... ${SECRET_NAME_CCS_VERSION}"
@@ -303,6 +390,12 @@ spec:
               echo "    - SECRET_NAME_DATAREFINERY_CHANNEL ...................... ${SECRET_NAME_DATAREFINERY_CHANNEL}"
               echo "    - SECRET_NAME_RABBITMQ_CHANNEL .......................... ${SECRET_NAME_RABBITMQ_CHANNEL}"
               echo "    - SECRET_NAME_ELASTICSEARCH_CHANNEL ..................... ${SECRET_NAME_ELASTICSEARCH_CHANNEL}"
+              echo "    - SECRET_NAME_AIOPENSCALE_VERSION ....................... ${SECRET_NAME_AIOPENSCALE_VERSION}"
+              echo "    - SECRET_NAME_AIOPENSCALE_CHANNEL ....................... ${SECRET_NAME_AIOPENSCALE_CHANNEL}"
+              echo "    - SECRET_NAME_SPSS_VERSION .............................. ${SECRET_NAME_SPSS_VERSION}"
+              echo "    - SECRET_NAME_SPSS_CHANNEL .............................. ${SECRET_NAME_SPSS_CHANNEL}"
+              echo "    - SECRET_NAME_CANVASBASE_CHANNEL ........................ ${SECRET_NAME_CANVASBASE_CHANNEL}"
+
               echo
 
 
@@ -311,6 +404,10 @@ spec:
               sm_update_secret $SECRET_NAME_LICENSING_VERSION "{\"licensing_version\": \"$LICENSING_VERSION\" }"
               sm_update_secret $SECRET_NAME_CPFS_CHANNEL "{\"cpfs_channel\": \"$CPFS_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_CPD_PLATFORM_CHANNEL "{\"cpd_platform_channel\": \"$CPD_PLATFORM_CHANNEL\" }"
+              sm_update_secret $SECRET_NAME_WML_VERSION "{\"wml_version\": \"$WML_VERSION\" }"
+              sm_update_secret $SECRET_NAME_WML_CHANNEL "{\"wml_channel\": \"$WML_CHANNEL\" }"
+              sm_update_secret $SECRET_NAME_SPARK_VERSION "{\"spark_version\": \"$SPARK_VERSION\" }"
+              sm_update_secret $SECRET_NAME_SPARK_CHANNEL "{\"spark_channel\": \"$SPARK_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_WSL_VERSION "{\"wsl_version\": \"$WSL_VERSION\" }"
               sm_update_secret $SECRET_NAME_WSL_CHANNEL "{\"wsl_channel\": \"$WSL_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_CCS_VERSION "{\"ccs_version\": \"$CCS_VERSION\" }"
@@ -321,7 +418,11 @@ spec:
               sm_update_secret $SECRET_NAME_DATAREFINERY_CHANNEL "{\"datarefinery_channel\": \"$DATAREFINERY_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_RABBITMQ_CHANNEL "{\"opencontent_rabbitmq_channel\": \"$RABBITMQ_CHANNEL\" }"
               sm_update_secret $SECRET_NAME_ELASTICSEARCH_CHANNEL "{\"opencontent_elasticsearch_channel\": \"$ELASTICSEARCH_CHANNEL\" }"
-
+              sm_update_secret $SECRET_NAME_AIOPENSCALE_VERSION "{\"aiopenscale_version\": \"$AIOPENSCALE_VERSION\" }"
+              sm_update_secret $SECRET_NAME_AIOPENSCALE_CHANNEL "{\"aiopenscale_channel\": \"$AIOPENSCALE_CHANNEL\" }"
+              sm_update_secret $SECRET_NAME_SPSS_VERSION "{\"spss_version\": \"$SPSS_VERSION\" }"
+              sm_update_secret $SECRET_NAME_SPSS_CHANNEL "{\"spss_channel\": \"$SPSS_CHANNEL\" }"
+              sm_update_secret $SECRET_NAME_CANVASBASE_CHANNEL "{\"canvasbase_channel\": \"$CANVASBASE_CHANNEL\" }"
 
               echo "Done"
 
