e3nsure dro postsync job fails appropraitely

diff --git a/applications/ibm-dro/templates/08-postsync-update-sm_Job.yaml b/applications/ibm-dro/templates/08-postsync-update-sm_Job.yaml
--- a/applications/ibm-dro/templates/08-postsync-update-sm_Job.yaml
+++ b/applications/ibm-dro/templates/08-postsync-update-sm_Job.yaml
@@ -87,8 +87,12 @@ spec:
               SM_AWS_ACCESS_KEY_ID=$(cat /etc/mas/creds/aws/aws_access_key_id)
               SM_AWS_SECRET_ACCESS_KEY=$(cat /etc/mas/creds/aws/aws_secret_access_key)
 
-              SECRET_NAME_DRO=${ACCOUNT_ID}/${CLUSTER_ID}/dro
+              echo "Fetching token from ibm-data-reporter-operator-api-token Secret in ${DRO_NAMESPACE}"
               export DRO_API_TOKEN=$(oc get secret ibm-data-reporter-operator-api-token -n ${DRO_NAMESPACE} -o jsonpath='{.data.token}' | base64 -d ; echo)
+              if [[ -z "${DRO_API_TOKEN}" ]]; then
+                echo "Failed to fetch token"
+                exit 1
+              fi
 
               # might as well take advantage of gitops_utils for sm_ functions as we're using the cli image
               source /mascli/functions/gitops_utils
@@ -101,6 +105,7 @@ spec:
               sm_login
 
               # aws secretsmanager create-secret --name ${SECRET_NAME} --secret-string "${SECRET_VALUE}"
+              SECRET_NAME_DRO=${ACCOUNT_ID}/${CLUSTER_ID}/dro
               sm_update_secret $SECRET_NAME_DRO "{\"dro_api_token\": \"$DRO_API_TOKEN\" }"
 
 
