Test database creation

diff --git a/instance-applications/120-ibm-dbs-rds-database/templates/01-dbs-rds-postsync-setup.yaml b/instance-applications/120-ibm-dbs-rds-database/templates/01-dbs-rds-postsync-setup.yaml
--- a/instance-applications/120-ibm-dbs-rds-database/templates/01-dbs-rds-postsync-setup.yaml
+++ b/instance-applications/120-ibm-dbs-rds-database/templates/01-dbs-rds-postsync-setup.yaml
@@ -111,6 +111,10 @@ spec:
               
               echo "✅ Certificate downloaded to /etc/mas/rds-ssl/global-bundle.pem"
 
+              echo "Installing required system libraries..."
+              microdnf install -y libxcrypt-compat || yum install -y libxcrypt-compat || dnf install -y libxcrypt-compat || true
+              echo "✅ System libraries installed"
+
               pip install ibm_db && \
               export SSL_CERT_PATH=/etc/mas/rds-ssl/global-bundle.pem && \
               python /etc/mas/dbs-rds-init-script/dbs-rds-init.py
